// src/Editor/EditorProjectLifecycleCapability.cpp
#include "EditorProjectLifecycleCapability.h"

#include "ActiveProjectAssemblyState.h"
#include "ProjectRootPath.h" // gte::ExecutableDirectory()
#include "../Core/Plugins/ProjectAssemblyBuildRunner.h" // ResolveCMakeBuildDirectory/ResolveProjectAssemblySourceRootDirectory/RunPlainCMakeReconfigureAndWait
#include "../Core/Plugins/ProjectAssemblyNameValidation.h"
// CONFIRMED (not a guess): the GTE_LOG_ERROR/GTE_LOG_INFO macros themselves
// are declared/defined in Core/Logging.h, NOT Core/LogSink.h - LogSink.h
// only carries the ILogSink interface/InstallLogSink() (what EditorHost.cpp
// calls once, at startup, to plug Logger in) and is NOT needed just to call
// the macros. Every other real call site in this codebase that only needs
// to LOG (never install a sink) includes Logging.h directly - e.g.
// Network/NetworkServer.cpp, Jobs/JobContinuation.cpp,
// Editor/ImGuiIdConflictGuard.cpp. Do not include LogSink.h here.
#include "../Core/Logging.h"

#include <fstream>
#include <system_error>

namespace gte {

namespace {

// The exact, minimal-viable-scaffold template content
// (PHASE0_MASTER_STRATEGY.md's own source document, Step 4) - a real,
// immediately-compileable stub. `name` is substituted only into the
// generated comment header and the RegisterProject symbol's own file
// name reference - never into any code path that affects compilation.
std::string BuildGameStubCppContent(const std::string& name)
{
    return
        "// " + name + "Game.cpp - generated by the Editor's \"Create New Project\" action.\n"
        "// This is your project's Game half's entry point. Add your own render\n"
        "// passes/ECS components/systems here, or use the \"Project\" panel's\n"
        "// right-click \"Create\" menu (once this project is open/active) to scaffold\n"
        "// a starting Render Pass / Compute Shader / Vertex+Fragment Shader pair.\n"
        "#include \"../Libraries/ProjectAssemblyExports.h\"\n"
        "#include \"../../../src/Core/Core.h\"\n"
        "\n"
        "namespace {\n"
        "\n"
        "void RegisterProject(gte::Core& /*core*/)\n"
        "{\n"
        "    // Intentionally empty - a freshly-created project registers nothing\n"
        "    // yet. See this file's own header comment above for how to add your\n"
        "    // first real feature.\n"
        "}\n"
        "\n"
        "} // namespace\n"
        "\n"
        "GTE_DEFINE_PROJECT_EXPORTS_GAME(RegisterProject)\n";
}

bool WriteTextFile(const std::filesystem::path& path, const std::string& content)
{
    std::ofstream stream(path, std::ios::binary);
    if (!stream.is_open()) {
        return false;
    }
    stream << content;
    return stream.good();
}

} // namespace

IProjectLifecycleCapability::CreateProjectOutcome EditorProjectLifecycleCapability::CreateNewProjectAssembly(
    const std::string& name)
{
    CreateProjectOutcome outcome;

    // Cheap, load-bearing defensive check that is NOT in either source
    // document verbatim, added here because it closes a real, honest gap:
    // `GTE_ENABLE_PROJECT_ASSEMBLIES` (default ON - confirmed real,
    // current CMakeCache.txt on this machine) is what gates BOTH root
    // CMakeLists.txt's own `Projects/*` CONFIGURE_DEPENDS auto-discovery
    // block (confirmed lines 1735-1741) AND Core::LoadProjectAssemblies()'s
    // own call site - if a build genuinely has this OFF, writing a new
    // project's files here would silently succeed while the project can
    // never actually be picked up by CMake at all (LDD-CP2's own
    // reconfigure step would run but find nothing new to configure,
    // since the whole `if(GTE_ENABLE_PROJECT_ASSEMBLIES AND ...)` block
    // that would `add_subdirectory()` it is compiled out of the CMake
    // script itself). Failing loudly here, before any filesystem write,
    // is strictly better than a "successful" Create that quietly can
    // never be compiled.
#if !GTE_ENABLE_PROJECT_ASSEMBLIES
    outcome.errorMessage = "this build was configured with GTE_ENABLE_PROJECT_ASSEMBLIES=OFF - "
        "Project Assemblies (including a brand-new one) cannot be created or loaded";
    return outcome;
#else
    std::string validationError;
    if (!IsValidProjectAssemblyIdentifierName(name, validationError)) {
        outcome.errorMessage = validationError;
        return outcome;
    }

    const std::filesystem::path executableDirectory = gte::ExecutableDirectory();
    const std::filesystem::path buildDirectory = ResolveCMakeBuildDirectory(executableDirectory);
    if (buildDirectory.empty()) {
        outcome.errorMessage = "could not resolve the CMake build directory - is this a real, configured build?";
        return outcome;
    }
    const std::filesystem::path sourceRoot = ResolveProjectAssemblySourceRootDirectory(buildDirectory);
    if (sourceRoot.empty()) {
        outcome.errorMessage = "could not resolve the project source directory - is this a real, configured CMake build?";
        return outcome;
    }
    // The real repo root - ResolveProjectAssemblySourceRootDirectory()
    // returns exactly "<repo root>/Projects" (PHASE1), so its own parent IS
    // the repo root, always. Computed exactly ONCE, here, and reused below
    // both for locating the template AND for the reconfigure call - do NOT
    // recompute this a second time via a different (and, in an earlier
    // draft of this file, subtly WRONG - it tested buildDirectory's own
    // parent instead of sourceRoot's) expression.
    const std::filesystem::path repoRoot = sourceRoot.parent_path();

    const std::filesystem::path projectDirectory = sourceRoot / name;
    if (std::filesystem::exists(projectDirectory)) {
        outcome.errorMessage = "a project or file named '" + name + "' already exists";
        return outcome;
    }

    const std::filesystem::path assetsDirectory = projectDirectory / "Assets";
    const std::filesystem::path librariesDirectory = projectDirectory / "Libraries";
    std::error_code errorCode;

    bool scaffoldOk = true;
    scaffoldOk = scaffoldOk && std::filesystem::create_directories(librariesDirectory, errorCode);
    scaffoldOk = scaffoldOk
        && WriteTextFile(librariesDirectory / "CMakeLists.txt", "gte_add_project(" + name + ")\n");
    // Byte-for-byte copy of the engine's own canonical template - never
    // hand-retyped (PHASE0_MASTER_STRATEGY.md Step 4's own reasoning: a
    // silent drift between the template and a hand-typed copy is exactly
    // the kind of bug a future engine change to that template would
    // otherwise reintroduce invisibly). Confirmed real, current path:
    // "<repo root>/cmake/templates/ProjectAssemblyExports.h".
    const std::filesystem::path templateSource = repoRoot / "cmake" / "templates" / "ProjectAssemblyExports.h";
    scaffoldOk = scaffoldOk
        && std::filesystem::copy_file(templateSource, librariesDirectory / "ProjectAssemblyExports.h",
               std::filesystem::copy_options::overwrite_existing, errorCode);
    scaffoldOk = scaffoldOk && std::filesystem::create_directories(assetsDirectory, errorCode);
    scaffoldOk = scaffoldOk
        && WriteTextFile(assetsDirectory / (name + "Game.cpp"), BuildGameStubCppContent(name));

    if (!scaffoldOk) {
        std::error_code removeError;
        std::filesystem::remove_all(projectDirectory, removeError);
        // `errorCode` is only ever SET by the two std::filesystem calls
        // above that take it (create_directories()/copy_file()) - the two
        // WriteTextFile() calls report failure through `scaffoldOk` alone
        // and never touch `errorCode` at all. Guard with `errorCode`'s own
        // bool conversion (true only when it actually represents an error)
        // before quoting its .message() - blindly appending
        // errorCode.message() unconditionally would, on a build where the
        // FIRST failing step was actually one of the WriteTextFile() calls,
        // silently print a stale/misleading "(The operation completed
        // successfully.)"-style message instead of an honest one.
        outcome.errorMessage = "failed to write the new project's scaffold files";
        if (errorCode) {
            outcome.errorMessage += " (" + errorCode.message() + ")";
        }
        GTE_LOG_ERROR("ProjectLifecycle", "CreateNewProjectAssembly('" + name + "'): " + outcome.errorMessage);
        return outcome;
    }

    // LDD-CP2 (PHASE0_MASTER_STRATEGY.md) - ALWAYS reconfigure,
    // unconditionally, regardless of whether CMake's own CONFIGURE_DEPENDS
    // glob would already have picked this project up on its own. See that
    // decision's own reasoning for why this campaign deliberately does not
    // try to detect/branch on which CMake behavior is actually true here.
    if (!RunPlainCMakeReconfigureAndWait(repoRoot, buildDirectory)) {
        outcome.errorMessage =
            "project files were written successfully, but the automatic CMake reconfigure step failed - "
            "see the engine log for the real cmake output; the project's files were left on disk so you "
            "can retry compiling manually once the underlying problem is fixed";
        GTE_LOG_ERROR("ProjectLifecycle", "CreateNewProjectAssembly('" + name + "'): " + outcome.errorMessage);
        return outcome;
    }

    ActiveProjectAssemblyState::Instance().SetActive(name, projectDirectory);

    outcome.success = true;
    outcome.createdSourceDirectory = projectDirectory.string();
    GTE_LOG_INFO("ProjectLifecycle", "CreateNewProjectAssembly('" + name + "'): created at " + outcome.createdSourceDirectory);
    return outcome;
#endif
}

} // namespace gte
