// src/Editor/EditorProjectLifecycleCapability.cpp
//
// PHASE0_MASTER_STRATEGY.md, Section 2.2 (editor-core-separation-17
// campaign) - OpenProjectAssembly() and OpenProjectAssemblyOnMainThread()
// are NOT interchangeable. OpenProjectAssembly() may BLOCK its own calling
// thread waiting for EditorHost::Run()'s own bridge-drain point to service
// it - calling it from the main thread itself deadlocks the whole Editor,
// since that drain point is reached earlier in the SAME frame's own call
// stack and cannot run again until this call returns. Always call
// OpenProjectAssembly() from a network route handler; always call
// OpenProjectAssemblyOnMainThread() from ImGui/main-thread code.
#include "EditorProjectLifecycleCapability.h"

#include "ActiveProjectAssemblyState.h"
#include "ProjectRootPath.h" // gte::ExecutableDirectory()
#include "../Core/Plugins/ProjectAssemblyBuildRunner.h" // ResolveCMakeBuildDirectory/ResolveProjectAssemblySourceRootDirectory/RunPlainCMakeReconfigureAndWait/ClassifyProjectAssemblyFolder/ProjectValidityTier
#include "../Core/Plugins/ProjectAssemblyNameValidation.h"
// CONFIRMED (not a guess): the GTE_LOG_ERROR/GTE_LOG_INFO macros themselves
// are declared/defined in Core/Logging.h, NOT Core/LogSink.h - LogSink.h
// only carries the ILogSink interface/InstallLogSink() (what EditorHost.cpp
// calls once, at startup, to plug Logger in) and is NOT needed just to call
// the macros. Every other real call site in this codebase that only needs
// to LOG (never install a sink) includes Logging.h directly - e.g.
// Network/NetworkServer.cpp, Jobs/JobContinuation.cpp,
// Editor/ImGuiIdConflictGuard.cpp. Do not include LogSink.h here.
#include "../Core/Logging.h"
// editor-core-separation-17 campaign (On-Engine Project Workflow plan,
// BIG-STEP 3), PHASE3 - needed for the full Core class definition
// (m_core->GetProjectAssemblyHost() below needs it - this header only
// forward-declares `class Core;`). Transitively pulls in
// Plugins/ProjectAssemblyHost.h too (confirmed by reading Core.h's own
// include list), so no separate include for that one is needed.
#include "../Core/Core.h"
// editor-core-separation-17 campaign, PHASE3 - GetHotReloadEngineStateMutex(),
// used below exactly like ActiveProjectAssemblyState::GetActive()'s own
// already-shipped precedent.
#include "../Core/Plugins/HotReloadEngineStateMutex.h"
// editor-core-separation-17 campaign, PHASE3 - the real
// ProjectLifecycleLoadCommandBridge::SubmitResult/
// LoadProjectAssemblyCommandRequest/LoadProjectAssemblyCommandResult types -
// this file's own header only forward-declares
// `class ProjectLifecycleLoadCommandBridge;`, which is not enough to call
// SubmitAndWait() or read its result fields.
#include "../Application/ProjectLifecycleLoadCommandBridge.h"

#include <algorithm> // editor-core-separation-18 campaign, PHASE1 - std::transform/std::find (CreateAssetScaffold()'s case-insensitive collision scan below).
#include <cctype>    // editor-core-separation-18 campaign, PHASE1 - std::tolower (ToLowerAscii() below).
#include <fstream>
#include <system_error>

namespace gte {

namespace {

// The exact, minimal-viable-scaffold template content
// (PHASE0_MASTER_STRATEGY.md's own source document, Step 4) - a real,
// immediately-compileable stub. `name` is substituted only into the
// generated comment header and the RegisterProject symbol's own file
// name reference - never into any code path that affects compilation.
std::string BuildGameStubCppContent(const std::string& name)
{
    return
        "// " + name + "Game.cpp - generated by the Editor's \"Create New Project\" action.\n"
        "// This is your project's Game half's entry point. Add your own render\n"
        "// passes/ECS components/systems here, or use the \"Project\" panel's\n"
        "// right-click \"Create\" menu (once this project is open/active) to scaffold\n"
        "// a starting Render Pass / Compute Shader / Vertex+Fragment Shader pair.\n"
        "#include \"../Libraries/ProjectAssemblyExports.h\"\n"
        "#include \"../../../src/Core/Core.h\"\n"
        "\n"
        "namespace {\n"
        "\n"
        "void RegisterProject(gte::Core& /*core*/)\n"
        "{\n"
        "    // Intentionally empty - a freshly-created project registers nothing\n"
        "    // yet. See this file's own header comment above for how to add your\n"
        "    // first real feature.\n"
        "}\n"
        "\n"
        "} // namespace\n"
        "\n"
        "GTE_DEFINE_PROJECT_EXPORTS_GAME(RegisterProject)\n";
}

bool WriteTextFile(const std::filesystem::path& path, const std::string& content)
{
    std::ofstream stream(path, std::ios::binary);
    if (!stream.is_open()) {
        return false;
    }
    stream << content;
    return stream.good();
}

// editor-core-separation-17 campaign, PHASE3 - maps each ProjectValidityTier
// to the exact string ProjectListEntry::tierName's own doc comment
// (Core/EditorCapabilities.h) promises.
std::string ToTierName(ProjectValidityTier tier)
{
    switch (tier) {
    case ProjectValidityTier::NotAProject: return "NotAProject";
    case ProjectValidityTier::NotBuildable: return "NotBuildable";
    case ProjectValidityTier::NotCompiled: return "NotCompiled";
    case ProjectValidityTier::Compiled: return "Compiled";
    case ProjectValidityTier::AlreadyLoaded: return "AlreadyLoaded";
    }
    return "NotAProject"; // unreachable - silences a "not all control paths return a value" warning.
}

// editor-core-separation-18 campaign (On-Engine Project Workflow plan,
// BIG-STEP 4), PHASE1 - a tiny, dependency-free "replace every occurrence
// of a literal token" helper - std::string::find/replace in a loop, exactly
// like this file's own existing style (no <regex> anywhere in src/Core/,
// matching ProjectAssemblyNameValidation.h's own stated convention).
std::string ReplaceAll(std::string text, const std::string& token, const std::string& replacement)
{
    std::size_t position = 0;
    while ((position = text.find(token, position)) != std::string::npos) {
        text.replace(position, token.size(), replacement);
        position += replacement.size();
    }
    return text;
}

// Kind 1 - Render Pass (Assets/<Name>RenderPass.cpp, ONE file). Grounded
// directly in Projects/ProjectAssemblyProbe/Assets/HelloGame.cpp's own real,
// live, currently-compiling call shape (RenderPassProvider's real two-
// parameter lambda signature, ProviderScope's real two-value enum -
// PHASE0_MASTER_STRATEGY.md, Section 2, corrects the master-plan file's own
// factually-wrong Kind-1 template sketch). Defines an ordinary, non-exported
// free function - NEVER calls GTE_DEFINE_PROJECT_EXPORTS_GAME() itself (Risk
// register item 1, PHASE0_MASTER_STRATEGY.md) - so wiring in more than one
// scaffolded Render Pass into the same project's RegisterProject() never
// produces a duplicate GTE_RegisterProject linker error.
std::string BuildRenderPassCppContent(const std::string& name)
{
    static const char* kTemplate =
        "// __NAME__RenderPass.cpp - generated by the Editor's \"Create -> Render\n"
        "// Pass\" action. This function does NOTHING until you call it - add\n"
        "// exactly one line, Register__NAME__RenderPass(core);, inside your\n"
        "// project's own RegisterProject() function (see Assets/<ProjectName>Game.cpp).\n"
        "#include \"../../../src/Core/Core.h\"\n"
        "#include \"../../../src/Renderer/RenderGraph/RenderGraphBuilder.h\"\n"
        "#include \"../../../src/Renderer/RenderGraph/RenderGraphTypes.h\"\n"
        "#include \"../../../src/Renderer/RenderGraph/RenderPipeline.h\"\n"
        "\n"
        "#include <vector>\n"
        "\n"
        "void Register__NAME__RenderPass(gte::Core& core)\n"
        "{\n"
        "    core.RegisterProjectRenderPassProvider(\"__NAME__.RenderPass\", gte::rg::ProviderScope::Once,\n"
        "        [](const gte::rg::RenderPassFrameContext& frame, std::vector<gte::rg::RenderPassDesc>& outPasses) {\n"
        "            // TODO: mint any transient texture via frame.builder.CreateTexture()\n"
        "            // BEFORE constructing a gte::rg::RenderPassDesc below, then append it\n"
        "            // via outPasses.push_back(std::move(desc)) - see\n"
        "            // docs/conventions/project-assembly-system.md, \"Capability #2\",\n"
        "            // Findings B/E/F, and Assets/HelloGame.cpp in\n"
        "            // Projects/ProjectAssemblyProbe/ for a complete, real, working\n"
        "            // example to copy from. If your pass writes a transient texture\n"
        "            // nobody else reads, also append it to frame.finalTextureOutputs,\n"
        "            // or RenderGraphCompiler's backward-reachability culling scan will\n"
        "            // silently drop this whole pass.\n"
        "            (void)frame;\n"
        "            (void)outPasses;\n"
        "        });\n"
        "}\n";
    return ReplaceAll(kTemplate, "__NAME__", name);
}

// Kind 2 - Compute Shader (TWO files: Assets/<Name>.comp +
// Assets/<Name>ComputePass.cpp).
std::string BuildComputeShaderGlslContent(const std::string& /*name*/)
{
    return
        "#version 450\n"
        "layout(local_size_x = 16, local_size_y = 16) in;\n"
        "void main() {\n"
        "    // TODO: your compute work here.\n"
        "}\n";
}

std::string BuildComputePassCppContent(const std::string& name)
{
    static const char* kTemplate =
        "// __NAME__ComputePass.cpp - generated by the Editor's \"Create -> Compute\n"
        "// Shader\" action. This function does NOTHING until you call it - add\n"
        "// exactly one line, Register__NAME__ComputePass(core);, inside your\n"
        "// project's own RegisterProject() function.\n"
        "#include \"../../../src/Core/Core.h\"\n"
        "#include \"../../../src/Renderer/RenderGraph/RenderGraphBuilder.h\"\n"
        "#include \"../../../src/Renderer/RenderGraph/RenderGraphTypes.h\"\n"
        "#include \"../../../src/Renderer/RenderGraph/RenderPipeline.h\"\n"
        "#include \"../../../src/Renderer/ComputePipeline.h\"\n"
        "#include \"../../../src/Renderer/ComputeDescriptorSet.h\"\n"
        "#include \"../../../src/Renderer/ComputeDispatch.h\"\n"
        "\n"
        "#include <optional>\n"
        "#include <vector>\n"
        "\n"
        "namespace {\n"
        "std::optional<gte::ComputePipeline> g___NAME__ComputePipeline;\n"
        "}\n"
        "\n"
        "void Register__NAME__ComputePass(gte::Core& core)\n"
        "{\n"
        "    // TODO: build g___NAME__ComputePipeline on first use (see\n"
        "    // Projects/ProjectAssemblyProbe/Assets/HelloGame.cpp for a complete,\n"
        "    // real, working example - Renderer::CreateComputePipeline(), NEVER a\n"
        "    // raw ComputePipeline constructor call), referencing the compiled\n"
        "    // shader at the bare relative path\n"
        "    // \"project_assemblies/shaders/__NAME__.comp.spv\", then register a\n"
        "    // render pass provider the same way the generated __NAME__RenderPass.cpp\n"
        "    // (if you also created one) does, whose execute step dispatches it.\n"
        "    (void)core;\n"
        "}\n";
    return ReplaceAll(kTemplate, "__NAME__", name);
}

// Kind 3 - Vertex/Fragment Shader Pair (TWO plain text files, no companion
// .cpp, matching the master-plan file's own explicit, narrower reading -
// Non-Goal: "does NOT build a full, opinionated graphics-pipeline
// scaffold").
std::string BuildVertexShaderContent(const std::string& /*name*/)
{
    return
        "#version 450\n"
        "void main() {\n"
        "    gl_Position = vec4(0.0, 0.0, 0.0, 1.0); // TODO: real vertex transform.\n"
        "}\n";
}

std::string BuildFragmentShaderContent(const std::string& /*name*/)
{
    return
        "#version 450\n"
        "layout(location = 0) out vec4 outColor;\n"
        "void main() {\n"
        "    outColor = vec4(1.0, 0.0, 1.0, 1.0); // Placeholder \"hot magenta\" - unmistakably a stub.\n"
        "}\n";
}

// One entry per file a given kind produces - {relativeFileName, content}.
// Order matters for createdFiles' own reported order, but NOT for
// correctness (the collision scan below checks every entry before writing
// any of them).
struct ScaffoldFileSpec {
    std::string relativeFileName;
    std::string content;
};

std::vector<ScaffoldFileSpec> BuildScaffoldFileSpecs(AssetScaffoldKind kind, const std::string& name)
{
    switch (kind) {
    case AssetScaffoldKind::RenderPass:
        return { { name + "RenderPass.cpp", BuildRenderPassCppContent(name) } };
    case AssetScaffoldKind::ComputeShader:
        return {
            { name + ".comp", BuildComputeShaderGlslContent(name) },
            { name + "ComputePass.cpp", BuildComputePassCppContent(name) },
        };
    case AssetScaffoldKind::ShaderPair:
        return {
            { name + ".vert", BuildVertexShaderContent(name) },
            { name + ".frag", BuildFragmentShaderContent(name) },
        };
    }
    return {}; // unreachable - silences a "not all control paths return a value" warning.
}

std::string ReminderMessageForKind(AssetScaffoldKind kind, const std::string& name)
{
    switch (kind) {
    case AssetScaffoldKind::RenderPass:
        return "remember to call Register" + name + "RenderPass(core) from your project's RegisterProject() function!";
    case AssetScaffoldKind::ComputeShader:
        return "remember to call Register" + name + "ComputePass(core) from your project's RegisterProject() function!";
    case AssetScaffoldKind::ShaderPair:
        return ""; // no companion .cpp is generated for this kind - nothing to wire in.
    }
    return "";
}

// Windows' own filesystem is case-INSENSITIVE for collision purposes -
// "Foo.comp" and "foo.comp" are the same file. Explicit ASCII lowercase
// comparison (never std::filesystem::exists() alone with the literal typed
// case) so this logic is honest about WHY it's correct and independently
// unit-testable without touching a real filesystem.
std::string ToLowerAscii(const std::string& text)
{
    std::string result = text;
    std::transform(result.begin(), result.end(), result.begin(),
        [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    return result;
}

} // namespace

IProjectLifecycleCapability::CreateProjectOutcome EditorProjectLifecycleCapability::CreateNewProjectAssembly(
    const std::string& name)
{
    CreateProjectOutcome outcome;

    // Cheap, load-bearing defensive check that is NOT in either source
    // document verbatim, added here because it closes a real, honest gap:
    // `GTE_ENABLE_PROJECT_ASSEMBLIES` (default ON - confirmed real,
    // current CMakeCache.txt on this machine) is what gates BOTH root
    // CMakeLists.txt's own `Projects/*` CONFIGURE_DEPENDS auto-discovery
    // block (confirmed lines 1735-1741) AND Core::LoadProjectAssemblies()'s
    // own call site - if a build genuinely has this OFF, writing a new
    // project's files here would silently succeed while the project can
    // never actually be picked up by CMake at all (LDD-CP2's own
    // reconfigure step would run but find nothing new to configure,
    // since the whole `if(GTE_ENABLE_PROJECT_ASSEMBLIES AND ...)` block
    // that would `add_subdirectory()` it is compiled out of the CMake
    // script itself). Failing loudly here, before any filesystem write,
    // is strictly better than a "successful" Create that quietly can
    // never be compiled.
#if !GTE_ENABLE_PROJECT_ASSEMBLIES
    outcome.errorMessage = "this build was configured with GTE_ENABLE_PROJECT_ASSEMBLIES=OFF - "
        "Project Assemblies (including a brand-new one) cannot be created or loaded";
    return outcome;
#else
    std::string validationError;
    if (!IsValidProjectAssemblyIdentifierName(name, validationError)) {
        outcome.errorMessage = validationError;
        return outcome;
    }

    const std::filesystem::path executableDirectory = gte::ExecutableDirectory();
    const std::filesystem::path buildDirectory = ResolveCMakeBuildDirectory(executableDirectory);
    if (buildDirectory.empty()) {
        outcome.errorMessage = "could not resolve the CMake build directory - is this a real, configured build?";
        return outcome;
    }
    const std::filesystem::path sourceRoot = ResolveProjectAssemblySourceRootDirectory(buildDirectory);
    if (sourceRoot.empty()) {
        outcome.errorMessage = "could not resolve the project source directory - is this a real, configured CMake build?";
        return outcome;
    }
    // The real repo root - ResolveProjectAssemblySourceRootDirectory()
    // returns exactly "<repo root>/Projects" (PHASE1), so its own parent IS
    // the repo root, always. Computed exactly ONCE, here, and reused below
    // both for locating the template AND for the reconfigure call - do NOT
    // recompute this a second time via a different (and, in an earlier
    // draft of this file, subtly WRONG - it tested buildDirectory's own
    // parent instead of sourceRoot's) expression.
    const std::filesystem::path repoRoot = sourceRoot.parent_path();

    const std::filesystem::path projectDirectory = sourceRoot / name;
    if (std::filesystem::exists(projectDirectory)) {
        outcome.errorMessage = "a project or file named '" + name + "' already exists";
        return outcome;
    }

    const std::filesystem::path assetsDirectory = projectDirectory / "Assets";
    const std::filesystem::path librariesDirectory = projectDirectory / "Libraries";
    std::error_code errorCode;

    bool scaffoldOk = true;
    scaffoldOk = scaffoldOk && std::filesystem::create_directories(librariesDirectory, errorCode);
    scaffoldOk = scaffoldOk
        && WriteTextFile(librariesDirectory / "CMakeLists.txt", "gte_add_project(" + name + ")\n");
    // Byte-for-byte copy of the engine's own canonical template - never
    // hand-retyped (PHASE0_MASTER_STRATEGY.md Step 4's own reasoning: a
    // silent drift between the template and a hand-typed copy is exactly
    // the kind of bug a future engine change to that template would
    // otherwise reintroduce invisibly). Confirmed real, current path:
    // "<repo root>/cmake/templates/ProjectAssemblyExports.h".
    const std::filesystem::path templateSource = repoRoot / "cmake" / "templates" / "ProjectAssemblyExports.h";
    scaffoldOk = scaffoldOk
        && std::filesystem::copy_file(templateSource, librariesDirectory / "ProjectAssemblyExports.h",
               std::filesystem::copy_options::overwrite_existing, errorCode);
    scaffoldOk = scaffoldOk && std::filesystem::create_directories(assetsDirectory, errorCode);
    scaffoldOk = scaffoldOk
        && WriteTextFile(assetsDirectory / (name + "Game.cpp"), BuildGameStubCppContent(name));

    if (!scaffoldOk) {
        std::error_code removeError;
        std::filesystem::remove_all(projectDirectory, removeError);
        // `errorCode` is only ever SET by the two std::filesystem calls
        // above that take it (create_directories()/copy_file()) - the two
        // WriteTextFile() calls report failure through `scaffoldOk` alone
        // and never touch `errorCode` at all. Guard with `errorCode`'s own
        // bool conversion (true only when it actually represents an error)
        // before quoting its .message() - blindly appending
        // errorCode.message() unconditionally would, on a build where the
        // FIRST failing step was actually one of the WriteTextFile() calls,
        // silently print a stale/misleading "(The operation completed
        // successfully.)"-style message instead of an honest one.
        outcome.errorMessage = "failed to write the new project's scaffold files";
        if (errorCode) {
            outcome.errorMessage += " (" + errorCode.message() + ")";
        }
        GTE_LOG_ERROR("ProjectLifecycle", "CreateNewProjectAssembly('" + name + "'): " + outcome.errorMessage);
        return outcome;
    }

    // LDD-CP2 (PHASE0_MASTER_STRATEGY.md) - ALWAYS reconfigure,
    // unconditionally, regardless of whether CMake's own CONFIGURE_DEPENDS
    // glob would already have picked this project up on its own. See that
    // decision's own reasoning for why this campaign deliberately does not
    // try to detect/branch on which CMake behavior is actually true here.
    if (!RunPlainCMakeReconfigureAndWait(repoRoot, buildDirectory)) {
        outcome.errorMessage =
            "project files were written successfully, but the automatic CMake reconfigure step failed - "
            "see the engine log for the real cmake output; the project's files were left on disk so you "
            "can retry compiling manually once the underlying problem is fixed";
        GTE_LOG_ERROR("ProjectLifecycle", "CreateNewProjectAssembly('" + name + "'): " + outcome.errorMessage);
        return outcome;
    }

    ActiveProjectAssemblyState::Instance().SetActive(name, projectDirectory);

    outcome.success = true;
    outcome.createdSourceDirectory = projectDirectory.string();
    GTE_LOG_INFO("ProjectLifecycle", "CreateNewProjectAssembly('" + name + "'): created at " + outcome.createdSourceDirectory);
    return outcome;
#endif
}

EditorProjectLifecycleCapability::PreLoadResult EditorProjectLifecycleCapability::ClassifyAndMarkActive(
    const std::string& name)
{
    PreLoadResult result;
#if !GTE_ENABLE_PROJECT_ASSEMBLIES
    result.outcome.errorMessage = "this build was configured with GTE_ENABLE_PROJECT_ASSEMBLIES=OFF";
    return result;
#else
    std::string validationError;
    if (!IsValidProjectAssemblyIdentifierName(name, validationError)) {
        result.outcome.errorMessage = validationError;
        return result;
    }

    const std::filesystem::path executableDirectory = gte::ExecutableDirectory();
    const std::filesystem::path buildDirectory = ResolveCMakeBuildDirectory(executableDirectory);
    const std::filesystem::path sourceRoot = buildDirectory.empty()
        ? std::filesystem::path{} : ResolveProjectAssemblySourceRootDirectory(buildDirectory);
    if (sourceRoot.empty()) {
        result.outcome.errorMessage = "could not resolve the project source directory - is this a real, configured CMake build?";
        return result;
    }

    const std::filesystem::path candidateFolder = sourceRoot / name;
    const std::filesystem::path outputDirectory = ResolveProjectAssemblyOutputDirectory(executableDirectory);

    std::vector<std::string> loadedDllFileNames;
    if (m_core != nullptr) {
        std::lock_guard<std::mutex> lock(GetHotReloadEngineStateMutex());
        loadedDllFileNames = m_core->GetProjectAssemblyHost().GetLoadedAssemblyFileNames();
    }

    const ProjectValidityTier tier = ClassifyProjectAssemblyFolder(candidateFolder, outputDirectory, loadedDllFileNames);
    if (tier == ProjectValidityTier::NotAProject) {
        result.outcome.errorMessage = "not a valid project folder (missing Libraries/CMakeLists.txt)";
        return result;
    }

    ActiveProjectAssemblyState::Instance().SetActive(name, candidateFolder);
    result.resolvedProjectName = name;
    result.outcome.success = true;

    switch (tier) {
    case ProjectValidityTier::NotBuildable:
        result.outcome.statusMessage = "opened '" + name + "' - no buildable source yet; use the Assets panel's "
            "Create menu to add a Render Pass/Compute Shader, or add your own .cpp file";
        break;
    case ProjectValidityTier::NotCompiled:
        result.outcome.statusMessage = "opened '" + name + "' - not yet compiled, use Compile to build it";
        break;
    case ProjectValidityTier::Compiled:
        result.outcome.statusMessage = "opened '" + name + "' - loading...";
        result.needsLoad = true;
        break;
    case ProjectValidityTier::AlreadyLoaded:
        result.outcome.statusMessage = "opened '" + name + "' - already loaded and running "
            "(use the existing Compile & Reload feature to update its code, not Open)";
        break;
    case ProjectValidityTier::NotAProject:
        break; // unreachable - handled above.
    }
    return result;
#endif
}

IProjectLifecycleCapability::OpenProjectOutcome EditorProjectLifecycleCapability::OpenProjectAssembly(
    const std::string& name)
{
    PreLoadResult pre = ClassifyAndMarkActive(name);
    if (!pre.outcome.success || !pre.needsLoad) {
        return pre.outcome;
    }
    if (m_loadCommandBridge == nullptr) {
        pre.outcome.statusMessage += " (warning: load command bridge unavailable - marked active only)";
        GTE_LOG_ERROR("ProjectLifecycle", "OpenProjectAssembly('" + name + "'): load command bridge unavailable");
        return pre.outcome;
    }
    LoadProjectAssemblyCommandRequest request;
    request.projectName = pre.resolvedProjectName;
    const ProjectLifecycleLoadCommandBridge::SubmitResult submit = m_loadCommandBridge->SubmitAndWait(request);
    pre.outcome.loadAttempted = true;
    if (submit.result.has_value()) {
        pre.outcome.loadSucceeded = submit.result->loadSucceeded;
        pre.outcome.statusMessage = pre.outcome.loadSucceeded
            ? ("opened '" + name + "' - loaded successfully")
            : ("opened '" + name + "' - marked active, but the load itself failed; see the engine log");
    } else {
        pre.outcome.statusMessage = "opened '" + name + "' - marked active, but the load request "
            + std::string(submit.alreadyPending ? "was rejected (another load is already in progress)" : "timed out");
    }
    GTE_LOG_INFO("ProjectLifecycle", "OpenProjectAssembly('" + name + "'): " + pre.outcome.statusMessage);
    return pre.outcome;
}

IProjectLifecycleCapability::OpenProjectOutcome EditorProjectLifecycleCapability::OpenProjectAssemblyOnMainThread(
    const std::string& name)
{
    PreLoadResult pre = ClassifyAndMarkActive(name);
    if (!pre.outcome.success || !pre.needsLoad) {
        return pre.outcome;
    }
    if (m_core == nullptr) {
        pre.outcome.statusMessage += " (warning: engine reference unavailable - marked active only)";
        GTE_LOG_ERROR("ProjectLifecycle", "OpenProjectAssemblyOnMainThread('" + name + "'): engine reference unavailable");
        return pre.outcome;
    }
    const std::filesystem::path outputDirectory = ResolveProjectAssemblyOutputDirectory(gte::ExecutableDirectory());
    pre.outcome.loadAttempted = true;
    pre.outcome.loadSucceeded =
        m_core->GetProjectAssemblyHost().LoadOneProjectAssemblyFromExactPath(
            outputDirectory / (pre.resolvedProjectName + "_Game.dll"), *m_core, m_editorHost)
        && m_core->GetProjectAssemblyHost().LoadOneProjectAssemblyFromExactPathIfExists(
            outputDirectory / (pre.resolvedProjectName + "_Editor.dll"), *m_core, m_editorHost);
    pre.outcome.statusMessage = pre.outcome.loadSucceeded
        ? ("opened '" + name + "' - loaded successfully")
        : ("opened '" + name + "' - marked active, but the load itself failed; see the engine log");
    GTE_LOG_INFO("ProjectLifecycle", "OpenProjectAssemblyOnMainThread('" + name + "'): " + pre.outcome.statusMessage);
    return pre.outcome;
}

std::vector<IProjectLifecycleCapability::ProjectListEntry> EditorProjectLifecycleCapability::ListProjectAssemblies()
{
    std::vector<ProjectListEntry> entries;
#if GTE_ENABLE_PROJECT_ASSEMBLIES
    const std::filesystem::path executableDirectory = gte::ExecutableDirectory();
    const std::filesystem::path buildDirectory = ResolveCMakeBuildDirectory(executableDirectory);
    if (buildDirectory.empty()) return entries;
    const std::filesystem::path sourceRoot = ResolveProjectAssemblySourceRootDirectory(buildDirectory);
    if (sourceRoot.empty() || !std::filesystem::is_directory(sourceRoot)) return entries;
    const std::filesystem::path outputDirectory = ResolveProjectAssemblyOutputDirectory(executableDirectory);

    std::vector<std::string> loadedDllFileNames;
    if (m_core != nullptr) {
        std::lock_guard<std::mutex> lock(GetHotReloadEngineStateMutex());
        loadedDllFileNames = m_core->GetProjectAssemblyHost().GetLoadedAssemblyFileNames();
    }

    std::error_code iterationError;
    for (const auto& entry : std::filesystem::directory_iterator(sourceRoot, iterationError)) {
        if (!entry.is_directory()) continue;
        const ProjectValidityTier tier = ClassifyProjectAssemblyFolder(entry.path(), outputDirectory, loadedDllFileNames);
        entries.push_back({ entry.path().filename().string(), ToTierName(tier) });
    }
#endif
    return entries;
}

void EditorProjectLifecycleCapability::SetLoadCommandBridge(ProjectLifecycleLoadCommandBridge& bridge) noexcept
{
    m_loadCommandBridge = &bridge;
}

void EditorProjectLifecycleCapability::SetEngineReferences(Core& core, EditorHost* editorHost) noexcept
{
    m_core = &core;
    m_editorHost = editorHost;
}

// editor-core-separation-18 campaign (On-Engine Project Workflow plan,
// BIG-STEP 4), PHASE1. See IAssetScaffoldingCapability's own doc comment
// (Core/EditorCapabilities.h) for the full contract. Deliberately has NO
// `#if !GTE_ENABLE_PROJECT_ASSEMBLIES` guard, unlike CreateNewProjectAssembly()/
// ClassifyAndMarkActive() above - when that macro is OFF, no project can
// ever become active in the first place (both of those methods' own
// identical guards mean SetActive() is never reached), so this method's own
// "no active project" check below already, structurally, covers this case
// for free.
IAssetScaffoldingCapability::ScaffoldOutcome EditorProjectLifecycleCapability::CreateAssetScaffold(
    AssetScaffoldKind kind, const std::string& name)
{
    ScaffoldOutcome outcome;

    const ActiveProjectAssemblyInfo active = ActiveProjectAssemblyState::Instance().GetActive();
    if (!active.hasActiveProject) {
        outcome.errorMessage = "no active project - use New Project or Open Project first";
        return outcome;
    }

    std::string validationError;
    if (!IsValidProjectAssemblyIdentifierName(name, validationError)) {
        outcome.errorMessage = validationError;
        return outcome;
    }

    const std::vector<ScaffoldFileSpec> fileSpecs = BuildScaffoldFileSpecs(kind, name);

    // Case-insensitive collision scan, EVERY file, BEFORE writing ANY of
    // them - all-or-nothing, mirrors CreateNewProjectAssembly()'s own
    // "never leave a half-written scaffold" rule.
    std::error_code iterationError;
    std::vector<std::string> existingLowerNames;
    for (const auto& entry : std::filesystem::directory_iterator(active.assetsDirectory, iterationError)) {
        if (!entry.is_regular_file()) continue;
        existingLowerNames.push_back(ToLowerAscii(entry.path().filename().string()));
    }
    for (const ScaffoldFileSpec& spec : fileSpecs) {
        const std::string lowerName = ToLowerAscii(spec.relativeFileName);
        if (std::find(existingLowerNames.begin(), existingLowerNames.end(), lowerName) != existingLowerNames.end()) {
            outcome.errorMessage = "a file named '" + spec.relativeFileName + "' already exists";
            return outcome;
        }
    }

    // A technically-possible-but-unlikely missing Assets/ folder (e.g. a
    // hand-authored/externally-copied Tier "NotBuildable" project) shouldn't
    // turn a legitimate project into a hard failure here - best-effort
    // create it, mirroring CreateNewProjectAssembly()'s own
    // create_directories() pattern, before the write loop below.
    std::error_code createDirectoriesError;
    std::filesystem::create_directories(active.assetsDirectory, createDirectoriesError);

    for (const ScaffoldFileSpec& spec : fileSpecs) {
        if (!WriteTextFile(active.assetsDirectory / spec.relativeFileName, spec.content)) {
            outcome.errorMessage = "failed to write '" + spec.relativeFileName + "'";
            GTE_LOG_ERROR("ProjectLifecycle", "CreateAssetScaffold('" + name + "'): " + outcome.errorMessage);
            return outcome;
        }
        outcome.createdFiles.push_back(spec.relativeFileName);
    }

    outcome.success = true;
    outcome.reminderMessage = ReminderMessageForKind(kind, name);
    GTE_LOG_INFO("ProjectLifecycle", "CreateAssetScaffold('" + name + "'): created " +
        std::to_string(outcome.createdFiles.size()) + " file(s) in " + active.assetsDirectory.string());
    return outcome;
}

} // namespace gte
