#pragma once

// Render Graph panel grouping tag for passes generated by a scaffolded
// project's own code (e.g. the Project Assembly hot-reload probe passes).
// Registered once, in Core::RegisterOffscreenRenderPipelineProviders().

#include "../../Renderer/RenderGraph/RenderGraphTypes.h"

namespace gte {

inline constexpr rg::RenderPassTag kProjectAuthoredPassTag{ 1ull << 6 };

} // namespace gte
