#pragma once

#include <cstdint>
#include <functional>

namespace gte {

// Cheap, POD, 8-byte identifier for an entity owned by a Registry (see
// Registry.h/EntityManager.h) - deliberately NOT a pointer or string,
// mirroring GpuResourceHandle (see Renderer/Memory/GpuResourceHandle.h)
// exactly: same index+generation shape, same "always generated by the
// owning manager, never invented by calling code" rule, for the same
// reason - cheap to copy/store/compare by the thousands. See AGENTS.md
// ("Entity-Component-System") for the full rationale.
//
// `index` is a direct slot index into EntityManager's internal array (an
// O(1) lookup, not a hash) - it is ALSO the key ComponentStorage<T> uses for
// its own sparse array (see ComponentStorage.h), so an entity's components
// are found by direct indexing too, never a hash lookup. `generation`
// guards against a stale Entity handle silently referring to a different
// entity that was later created in the same (reused) slot - this isn't
// theoretical: DestroyEntity() followed by CreateEntity() can and does
// reuse the just-freed slot (see EntityManager.cpp).
struct Entity {
    std::uint32_t index = 0;
    std::uint32_t generation = 0; // 0 == never assigned / invalid.

    bool IsValid() const noexcept { return generation != 0; }

    friend bool operator==(const Entity& a, const Entity& b) noexcept
    {
        return a.index == b.index && a.generation == b.generation;
    }
    friend bool operator!=(const Entity& a, const Entity& b) noexcept
    {
        return !(a == b);
    }
};

inline constexpr Entity kInvalidEntity{};

} // namespace gte

// std::hash specialization so Entity can be used directly as an
// unordered_map/unordered_set key (e.g. a future Editor Hierarchy selection
// set) without every caller having to write its own hasher.
namespace std {
template <>
struct hash<gte::Entity> {
    std::size_t operator()(const gte::Entity& e) const noexcept
    {
        return static_cast<std::size_t>((static_cast<std::uint64_t>(e.index) << 32) | e.generation);
    }
};
} // namespace std
