// Tier-1 tests for src/Editor/EditorProjectLifecycleCapability.h/.cpp's new
// IAssetScaffoldingCapability::CreateAssetScaffold() addition
// (editor-core-separation-18 campaign, On-Engine Project Workflow plan,
// BIG-STEP 4, PHASE1 - PHASE1_ASSET_SCAFFOLDING_CAPABILITY_AND_TEMPLATES.md,
// STEP 4).
//
// Mechanically confirmed correction, restated here so it is never silently
// re-litigated: BuildScaffoldFileSpecs()/ReminderMessageForKind()/every
// Build...Content() template builder/ToLowerAscii()/ReplaceAll() all live
// inside an UNNAMED (anonymous) namespace physically inside
// EditorProjectLifecycleCapability.cpp - they have internal linkage and are
// NOT visible/callable from this separate test .cpp file at all. This
// exactly matches this same file's own pre-existing convention
// (BuildGameStubCppContent()/WriteTextFile()/ToTierName() have ZERO direct
// unit tests anywhere in tests/ today - only ever exercised INDIRECTLY,
// through CreateNewProjectAssembly()/OpenProjectAssembly()). Every test
// below exercises the templates/collision logic ONLY through the one real
// public entry point, CreateAssetScaffold().
//
// File location: tests/Editor/ (NOT tests/Core/Plugins/) -
// EditorProjectLifecycleCapability is gte_editor-tier code (physically
// compiled into the gte_editor static library, exactly like every
// Network/*ProjectEndpointEndToEndTests.cpp file that already links against
// it) - tests/Core/Plugins/ is reserved for genuinely gte_core-tier-only
// code needing no gte_editor symbol at all.
//
// Test-isolation hazard (made explicit so it is never silently
// reintroduced): ActiveProjectAssemblyState is a real, process-wide Meyers
// singleton shared by EVERY test in GreatTamanaEngineTests.exe, including
// CreateProjectEndpointEndToEndTests.cpp/OpenProjectEndpointEndToEndTests.cpp,
// both of which already legitimately call SetActive() as a side effect of
// their own successful paths - gtest gives no cross-file test-order
// guarantee, so this file can NEVER assume GetActive().hasActiveProject
// starts false. Every test below captures a "before" snapshot first
// (OpenProjectEndpointEndToEndTests.cpp's own
// OpenProjectOnTier0OrNonexistentNameReturns400AndDoesNotMutateActiveState
// idiom), and the one test that genuinely needs hasActiveProject == false
// explicitly forces it via Clear() then restores "before" afterward.

#include "Editor/ActiveProjectAssemblyState.h"
#include "Editor/EditorProjectLifecycleCapability.h"

#include <gtest/gtest.h>

#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

namespace gte {
namespace {

// A unique-per-test-run temp directory, cleaned up (best-effort) at the end
// of each test via its own destructor - never touches the real, production
// Projects/ tree. Mirrors
// tests/Core/Plugins/ProjectAssemblyBuildRunnerTierClassificationTests.cpp's
// own TempOutputDirectory helper for the create/cleanup SHAPE only.
class TempScratchProjectDirectory {
public:
    explicit TempScratchProjectDirectory(const std::string& uniqueSuffix)
        : m_path(std::filesystem::temp_directory_path() / ("gte_asset_scaffold_tests_" + uniqueSuffix))
    {
        std::filesystem::remove_all(m_path);
        std::filesystem::create_directories(m_path / "Assets");
    }

    ~TempScratchProjectDirectory()
    {
        std::error_code ignored;
        std::filesystem::remove_all(m_path, ignored);
    }

    const std::filesystem::path& Path() const { return m_path; }
    std::filesystem::path AssetsPath() const { return m_path / "Assets"; }

private:
    std::filesystem::path m_path;
};

std::string ReadFile(const std::filesystem::path& path)
{
    std::ifstream stream(path, std::ios::binary);
    return std::string((std::istreambuf_iterator<char>(stream)), std::istreambuf_iterator<char>());
}

// editor-core-separation-24 campaign ("Project Assembly On-Screen Render
// Feature Compositing", BIG-STEP 2), PHASE6 - a byte-for-byte copy of the
// REAL, currently-shipped BuildGameStubCppContent() template
// (EditorProjectLifecycleCapability.cpp, PHASE2's own anchor-bearing
// version) so these tests exercise CreateAssetScaffold()'s new
// ScreenPostProcessPass branch against a REALISTIC <ProjectName>Game.cpp -
// both anchor comment BLOCKS (seven physical lines each), not a simplified
// single-line stand-in. This is a deliberate duplication (the real function
// has internal linkage and is not reachable from this separate test .cpp
// file), exactly like ScreenPassAutoWireTests.cpp's own equivalent fixture
// content.
std::string BuildScratchGameCppWithAnchors(const std::string& name)
{
    return
        "// " + name + "Game.cpp - generated by the Editor's \"Create New Project\" action.\n"
        "// This is your project's Game half's entry point. Add your own render\n"
        "// passes/ECS components/systems here, or use the \"Project\" panel's\n"
        "// right-click \"Create\" menu (once this project is open/active) to scaffold\n"
        "// a starting Render Pass / Compute Shader / Vertex+Fragment Shader pair.\n"
        "#include \"../Libraries/ProjectAssemblyExports.h\"\n"
        "#include \"../../../src/Core/Core.h\"\n"
        "\n"
        "// GTE_AUTO_REGISTER_FORWARD_DECLARATIONS - do not remove or edit this\n"
        "// line. The Editor's \"Create\" scaffolding tools (Render Pass / Compute\n"
        "// Shader / Screen Post-Process Pass) insert a forward declaration for\n"
        "// each newly-scaffolded Register<Name>...(core) function directly BELOW\n"
        "// this line, automatically. Removing this comment does not break\n"
        "// anything - a future scaffold action simply cannot auto-wire itself in\n"
        "// anymore, and falls back to reminding you to wire it in by hand instead.\n"
        "\n"
        "namespace {\n"
        "\n"
        "void RegisterProject(gte::Core& core)\n"
        "{\n"
        "    // GTE_AUTO_REGISTER_ANCHOR - do not remove or edit this line. The\n"
        "    // Editor's \"Create\" scaffolding tools insert their own\n"
        "    // Register<Name>...(core); call directly ABOVE this comment,\n"
        "    // automatically, when they can find it. Removing this comment does\n"
        "    // not break anything - a future scaffold action simply cannot\n"
        "    // auto-wire itself in anymore, and falls back to reminding you to\n"
        "    // wire it in by hand instead.\n"
        "}\n"
        "\n"
        "} // namespace\n"
        "\n"
        "GTE_DEFINE_PROJECT_EXPORTS_GAME(RegisterProject)\n";
}

// RAII helper restoring ActiveProjectAssemblyState to whatever it was before
// this test touched it - every test uses this so no scratch project name
// or "no active project" state ever leaks into whichever test happens to
// run next in this same binary.
class ActiveProjectStateRestorer {
public:
    ActiveProjectStateRestorer() : m_before(ActiveProjectAssemblyState::Instance().GetActive()) {}
    ~ActiveProjectStateRestorer()
    {
        if (m_before.hasActiveProject) {
            ActiveProjectAssemblyState::Instance().SetActive(m_before.name, m_before.sourceDirectory);
        } else {
            ActiveProjectAssemblyState::Instance().Clear();
        }
    }

private:
    ActiveProjectAssemblyInfo m_before;
};

} // namespace

TEST(AssetScaffoldTemplateTest, NoActiveProjectFailsWithClearMessage)
{
    ActiveProjectStateRestorer restorer;
    ActiveProjectAssemblyState::Instance().Clear();

    EditorProjectLifecycleCapability capability;
    const IAssetScaffoldingCapability::ScaffoldOutcome outcome =
        capability.CreateAssetScaffold(AssetScaffoldKind::RenderPass, "Foo");

    EXPECT_FALSE(outcome.success);
    EXPECT_NE(outcome.errorMessage.find("no active project"), std::string::npos);
    EXPECT_TRUE(outcome.createdFiles.empty());
}

TEST(AssetScaffoldTemplateTest, RenderPassKindCreatesOneFileWithSubstitutedNameAndReminder)
{
    ActiveProjectStateRestorer restorer;
    TempScratchProjectDirectory scratch("RenderPass");
    ActiveProjectAssemblyState::Instance().SetActive("ScratchProject", scratch.Path());

    EditorProjectLifecycleCapability capability;
    const IAssetScaffoldingCapability::ScaffoldOutcome outcome =
        capability.CreateAssetScaffold(AssetScaffoldKind::RenderPass, "Foo");

    ASSERT_TRUE(outcome.success) << outcome.errorMessage;
    ASSERT_EQ(outcome.createdFiles.size(), 1u);
    EXPECT_EQ(outcome.createdFiles[0], "FooRenderPass.cpp");
    EXPECT_FALSE(outcome.reminderMessage.empty());
    EXPECT_NE(outcome.reminderMessage.find("RegisterFooRenderPass"), std::string::npos);

    ASSERT_TRUE(std::filesystem::exists(scratch.AssetsPath() / "FooRenderPass.cpp"));
    const std::string content = ReadFile(scratch.AssetsPath() / "FooRenderPass.cpp");
    EXPECT_EQ(content.find("__NAME__"), std::string::npos);
    EXPECT_NE(content.find("RegisterFooRenderPass"), std::string::npos);
    EXPECT_NE(content.find("\"Foo.RenderPass\""), std::string::npos);
    // Regression proof for the corrected template (PHASE0_MASTER_STRATEGY.md,
    // Section 2) - the real, two-value ProviderScope enum and the real,
    // two-parameter RenderPassProvider lambda signature, never the
    // master-plan file's own non-compiling sketch.
    EXPECT_NE(content.find("gte::rg::ProviderScope::Once"), std::string::npos);
    EXPECT_NE(content.find("std::vector<gte::rg::RenderPassDesc>& outPasses"), std::string::npos);
}

TEST(AssetScaffoldTemplateTest, ComputeShaderKindCreatesTwoFilesWithSubstitutedNameAndReminder)
{
    ActiveProjectStateRestorer restorer;
    TempScratchProjectDirectory scratch("ComputeShader");
    ActiveProjectAssemblyState::Instance().SetActive("ScratchProject", scratch.Path());

    EditorProjectLifecycleCapability capability;
    const IAssetScaffoldingCapability::ScaffoldOutcome outcome =
        capability.CreateAssetScaffold(AssetScaffoldKind::ComputeShader, "Foo");

    ASSERT_TRUE(outcome.success) << outcome.errorMessage;
    ASSERT_EQ(outcome.createdFiles.size(), 2u);
    EXPECT_EQ(outcome.createdFiles[0], "Foo.comp");
    EXPECT_EQ(outcome.createdFiles[1], "FooComputePass.cpp");
    EXPECT_FALSE(outcome.reminderMessage.empty());
    EXPECT_NE(outcome.reminderMessage.find("RegisterFooComputePass"), std::string::npos);

    ASSERT_TRUE(std::filesystem::exists(scratch.AssetsPath() / "Foo.comp"));
    ASSERT_TRUE(std::filesystem::exists(scratch.AssetsPath() / "FooComputePass.cpp"));
    const std::string computeContent = ReadFile(scratch.AssetsPath() / "Foo.comp");
    EXPECT_EQ(computeContent.find("__NAME__"), std::string::npos);
    EXPECT_NE(computeContent.find("#version 450"), std::string::npos);
    const std::string passContent = ReadFile(scratch.AssetsPath() / "FooComputePass.cpp");
    EXPECT_EQ(passContent.find("__NAME__"), std::string::npos);
    EXPECT_NE(passContent.find("RegisterFooComputePass"), std::string::npos);
    EXPECT_NE(passContent.find("g_FooComputePipeline"), std::string::npos);
}

TEST(AssetScaffoldTemplateTest, ShaderPairKindCreatesTwoFilesWithNoReminderAndNoCompanionCpp)
{
    ActiveProjectStateRestorer restorer;
    TempScratchProjectDirectory scratch("ShaderPair");
    ActiveProjectAssemblyState::Instance().SetActive("ScratchProject", scratch.Path());

    EditorProjectLifecycleCapability capability;
    const IAssetScaffoldingCapability::ScaffoldOutcome outcome =
        capability.CreateAssetScaffold(AssetScaffoldKind::ShaderPair, "Foo");

    ASSERT_TRUE(outcome.success) << outcome.errorMessage;
    ASSERT_EQ(outcome.createdFiles.size(), 2u);
    EXPECT_EQ(outcome.createdFiles[0], "Foo.vert");
    EXPECT_EQ(outcome.createdFiles[1], "Foo.frag");
    EXPECT_TRUE(outcome.reminderMessage.empty());

    ASSERT_TRUE(std::filesystem::exists(scratch.AssetsPath() / "Foo.vert"));
    ASSERT_TRUE(std::filesystem::exists(scratch.AssetsPath() / "Foo.frag"));
    EXPECT_FALSE(std::filesystem::exists(scratch.AssetsPath() / "Foo.cpp"));
    const std::string vertContent = ReadFile(scratch.AssetsPath() / "Foo.vert");
    EXPECT_NE(vertContent.find("gl_Position"), std::string::npos);
    const std::string fragContent = ReadFile(scratch.AssetsPath() / "Foo.frag");
    EXPECT_NE(fragContent.find("outColor"), std::string::npos);
}

TEST(AssetScaffoldTemplateTest, SameNameSameKindCalledTwiceRejectsSecondCallAndLeavesOriginalFileUntouched)
{
    ActiveProjectStateRestorer restorer;
    TempScratchProjectDirectory scratch("DuplicateSameCase");
    ActiveProjectAssemblyState::Instance().SetActive("ScratchProject", scratch.Path());

    EditorProjectLifecycleCapability capability;
    const IAssetScaffoldingCapability::ScaffoldOutcome first =
        capability.CreateAssetScaffold(AssetScaffoldKind::RenderPass, "Foo");
    ASSERT_TRUE(first.success) << first.errorMessage;
    const std::string originalContent = ReadFile(scratch.AssetsPath() / "FooRenderPass.cpp");
    const std::filesystem::file_time_type originalMtime =
        std::filesystem::last_write_time(scratch.AssetsPath() / "FooRenderPass.cpp");

    const IAssetScaffoldingCapability::ScaffoldOutcome second =
        capability.CreateAssetScaffold(AssetScaffoldKind::RenderPass, "Foo");

    EXPECT_FALSE(second.success);
    EXPECT_NE(second.errorMessage.find("already exists"), std::string::npos);
    EXPECT_TRUE(second.createdFiles.empty());

    // The original file's content/mtime genuinely never changed - a real,
    // mechanical proof, not an assumed side effect.
    EXPECT_EQ(ReadFile(scratch.AssetsPath() / "FooRenderPass.cpp"), originalContent);
    EXPECT_EQ(std::filesystem::last_write_time(scratch.AssetsPath() / "FooRenderPass.cpp"), originalMtime);
}

TEST(AssetScaffoldTemplateTest, SameNameDifferentCaseCalledTwiceRejectsSecondCallCaseInsensitively)
{
    ActiveProjectStateRestorer restorer;
    TempScratchProjectDirectory scratch("DuplicateDifferentCase");
    ActiveProjectAssemblyState::Instance().SetActive("ScratchProject", scratch.Path());

    EditorProjectLifecycleCapability capability;
    const IAssetScaffoldingCapability::ScaffoldOutcome first =
        capability.CreateAssetScaffold(AssetScaffoldKind::ComputeShader, "Foo");
    ASSERT_TRUE(first.success) << first.errorMessage;

    // "foo" vs. "Foo" - a different-case variant of the same base name -
    // must ALSO be rejected (case-insensitive collision, LDD-CA# in
    // PHASE0_MASTER_STRATEGY.md / risk register item 5).
    const IAssetScaffoldingCapability::ScaffoldOutcome second =
        capability.CreateAssetScaffold(AssetScaffoldKind::ComputeShader, "foo");

    EXPECT_FALSE(second.success);
    EXPECT_NE(second.errorMessage.find("already exists"), std::string::npos);
    EXPECT_TRUE(second.createdFiles.empty());
}

// editor-core-separation-24 campaign ("Project Assembly On-Screen Render
// Feature Compositing", BIG-STEP 2), PHASE6
// (PHASE6_CREATE_ASSET_SCAFFOLD_DISPATCH_BRANCH.md, Step 4) - the four
// required scenarios below exercise CreateAssetScaffold()'s new
// AssetScaffoldKind::ScreenPostProcessPass branch end to end through the
// real, public CreateAssetScaffold() entry point, wiring together PHASE3's
// BuildScreenPostProcessPassCppContent(), PHASE4's TryAutoWireRegisterCall(),
// and PHASE5's ComputeNextScreenPassPriority() for the first time.

TEST(AssetScaffoldTemplateTest, ScreenPostProcessPassNameTooLongRejectedWithZeroFilesWritten)
{
    ActiveProjectStateRestorer restorer;
    TempScratchProjectDirectory scratch("ScreenPassNameTooLong");
    ActiveProjectAssemblyState::Instance().SetActive("ScratchProject", scratch.Path());

    EditorProjectLifecycleCapability capability;
    // The generated debug name is "<name>.ScreenTint" (11 extra characters) -
    // GtePluginRenderFeatureDescriptor::name has a 63-usable-byte limit, so a
    // 60-character name (60 + 11 = 71 > 63) must be rejected BEFORE any file
    // is written, per this phase's own Step 3/Locked Decision 4.
    const std::string longName(60, 'A');
    const IAssetScaffoldingCapability::ScaffoldOutcome outcome =
        capability.CreateAssetScaffold(AssetScaffoldKind::ScreenPostProcessPass, longName);

    EXPECT_FALSE(outcome.success);
    EXPECT_NE(outcome.errorMessage.find("too long"), std::string::npos);
    EXPECT_TRUE(outcome.createdFiles.empty());
    EXPECT_FALSE(std::filesystem::exists(scratch.AssetsPath() / (longName + "ScreenPass.cpp")));
}

TEST(AssetScaffoldTemplateTest, ScreenPostProcessPassFirstScaffoldWithBothAnchorsAutoWiresAtPriorityZero)
{
    ActiveProjectStateRestorer restorer;
    TempScratchProjectDirectory scratch("ScreenPassFirstAutoWire");
    ActiveProjectAssemblyState::Instance().SetActive("ScratchProject", scratch.Path());

    // Write the target <ProjectName>Game.cpp BY HAND, with both real PHASE2
    // anchor comment blocks present, exactly as a real
    // CreateNewProjectAssembly()-created project's Assets/ScratchProjectGame.cpp
    // would look - this scratch fixture is not itself created through that
    // real entry point.
    const std::filesystem::path gameCppPath = scratch.AssetsPath() / "ScratchProjectGame.cpp";
    {
        std::ofstream stream(gameCppPath, std::ios::binary);
        stream << BuildScratchGameCppWithAnchors("ScratchProject");
    }

    EditorProjectLifecycleCapability capability;
    const IAssetScaffoldingCapability::ScaffoldOutcome outcome =
        capability.CreateAssetScaffold(AssetScaffoldKind::ScreenPostProcessPass, "Foo");

    ASSERT_TRUE(outcome.success) << outcome.errorMessage;
    ASSERT_EQ(outcome.createdFiles.size(), 1u);
    EXPECT_EQ(outcome.createdFiles[0], "FooScreenPass.cpp");
    EXPECT_NE(outcome.reminderMessage.find("automatically wired"), std::string::npos);

    ASSERT_TRUE(std::filesystem::exists(scratch.AssetsPath() / "FooScreenPass.cpp"));
    const std::string screenPassContent = ReadFile(scratch.AssetsPath() / "FooScreenPass.cpp");
    EXPECT_EQ(screenPassContent.find("__NAME__"), std::string::npos);
    EXPECT_NE(screenPassContent.find("RegisterFooScreenPass"), std::string::npos);
    EXPECT_NE(screenPassContent.find("\"Foo.ScreenTint\""), std::string::npos);
    // better-render-pass-1 campaign, PHASE9 (Decision D3) - the generated
    // template now calls core.AddScreenPostProcessPass(), whose signature
    // puts `priority` as its LAST positional argument (after the callback/
    // blendMode) - the generated line therefore ends in a closing paren +
    // semicolon ("/*priority=*/0);"), never a trailing comma like the old
    // core.RegisterProjectRenderFeature()-based template did.
    EXPECT_NE(screenPassContent.find("/*priority=*/0);"), std::string::npos);
    EXPECT_NE(screenPassContent.find("core.AddScreenPostProcessPass("), std::string::npos);

    // The scratch project's own Game.cpp now contains the correct forward
    // declaration + call line, auto-wired in.
    const std::string gameCppContent = ReadFile(gameCppPath);
    EXPECT_NE(gameCppContent.find("void RegisterFooScreenPass(gte::Core& core);"), std::string::npos);
    EXPECT_NE(gameCppContent.find("    RegisterFooScreenPass(core);"), std::string::npos);
}

TEST(AssetScaffoldTemplateTest, ScreenPostProcessPassSecondScaffoldSameProjectIncrementsPriorityAndKeepsFirstCallIntact)
{
    ActiveProjectStateRestorer restorer;
    TempScratchProjectDirectory scratch("ScreenPassSecondAutoWire");
    ActiveProjectAssemblyState::Instance().SetActive("ScratchProject", scratch.Path());

    const std::filesystem::path gameCppPath = scratch.AssetsPath() / "ScratchProjectGame.cpp";
    {
        std::ofstream stream(gameCppPath, std::ios::binary);
        stream << BuildScratchGameCppWithAnchors("ScratchProject");
    }

    EditorProjectLifecycleCapability capability;
    const IAssetScaffoldingCapability::ScaffoldOutcome first =
        capability.CreateAssetScaffold(AssetScaffoldKind::ScreenPostProcessPass, "Foo");
    ASSERT_TRUE(first.success) << first.errorMessage;

    const IAssetScaffoldingCapability::ScaffoldOutcome second =
        capability.CreateAssetScaffold(AssetScaffoldKind::ScreenPostProcessPass, "Bar");
    ASSERT_TRUE(second.success) << second.errorMessage;
    ASSERT_EQ(second.createdFiles.size(), 1u);
    EXPECT_EQ(second.createdFiles[0], "BarScreenPass.cpp");
    EXPECT_NE(second.reminderMessage.find("automatically wired"), std::string::npos);

    const std::string secondContent = ReadFile(scratch.AssetsPath() / "BarScreenPass.cpp");
    // better-render-pass-1 campaign, PHASE9 (Decision D3) - see the matching
    // comment in the first-scaffold test above for why this is now
    // "/*priority=*/1);" (closing paren), not a trailing comma.
    EXPECT_NE(secondContent.find("/*priority=*/1);"), std::string::npos);

    // The FIRST scaffold's own forward declaration/call line is still
    // present, unduplicated, alongside the new one - the concrete regression
    // proof for PHASE4's "second insertion point resolution thrown off by
    // the first" hazard, exercised here through the real dispatch branch.
    const std::string gameCppContent = ReadFile(gameCppPath);
    EXPECT_NE(gameCppContent.find("void RegisterFooScreenPass(gte::Core& core);"), std::string::npos);
    EXPECT_NE(gameCppContent.find("    RegisterFooScreenPass(core);"), std::string::npos);
    EXPECT_NE(gameCppContent.find("void RegisterBarScreenPass(gte::Core& core);"), std::string::npos);
    EXPECT_NE(gameCppContent.find("    RegisterBarScreenPass(core);"), std::string::npos);
}

TEST(AssetScaffoldTemplateTest, ScreenPostProcessPassOldProjectMissingGameCppFallsBackToManualReminder)
{
    ActiveProjectStateRestorer restorer;
    TempScratchProjectDirectory scratch("ScreenPassOldProjectMissingFile");
    ActiveProjectAssemblyState::Instance().SetActive("ScratchProject", scratch.Path());
    // Deliberately do NOT create Assets/ScratchProjectGame.cpp at all -
    // TryAutoWireRegisterCall()'s computed target path must not exist for
    // this scenario to exercise the fallback branch.

    EditorProjectLifecycleCapability capability;
    const IAssetScaffoldingCapability::ScaffoldOutcome outcome =
        capability.CreateAssetScaffold(AssetScaffoldKind::ScreenPostProcessPass, "Foo");

    ASSERT_TRUE(outcome.success) << outcome.errorMessage;
    ASSERT_EQ(outcome.createdFiles.size(), 1u);
    EXPECT_EQ(outcome.createdFiles[0], "FooScreenPass.cpp");
    EXPECT_NE(outcome.reminderMessage.find("could not auto-wire"), std::string::npos);
    EXPECT_NE(outcome.reminderMessage.find("RegisterFooScreenPass(core)"), std::string::npos);
    ASSERT_TRUE(std::filesystem::exists(scratch.AssetsPath() / "FooScreenPass.cpp"));
    EXPECT_FALSE(std::filesystem::exists(scratch.AssetsPath() / "ScratchProjectGame.cpp"));
}

TEST(AssetScaffoldTemplateTest, ScreenPostProcessPassOldProjectGameCppWithNoAnchorsFallsBackAndLeavesFileUnchanged)
{
    ActiveProjectStateRestorer restorer;
    TempScratchProjectDirectory scratch("ScreenPassOldProjectNoAnchors");
    ActiveProjectAssemblyState::Instance().SetActive("ScratchProject", scratch.Path());

    const std::filesystem::path gameCppPath = scratch.AssetsPath() / "ScratchProjectGame.cpp";
    const std::string originalGameCppContent =
        "// ScratchProjectGame.cpp - a pre-auto-wiring-era project file, no anchors.\n"
        "#include \"../Libraries/ProjectAssemblyExports.h\"\n"
        "#include \"../../../src/Core/Core.h\"\n"
        "\n"
        "namespace {\n"
        "\n"
        "void RegisterProject(gte::Core& /*core*/)\n"
        "{\n"
        "    // Intentionally empty.\n"
        "}\n"
        "\n"
        "} // namespace\n"
        "\n"
        "GTE_DEFINE_PROJECT_EXPORTS_GAME(RegisterProject)\n";
    {
        std::ofstream stream(gameCppPath, std::ios::binary);
        stream << originalGameCppContent;
    }

    EditorProjectLifecycleCapability capability;
    const IAssetScaffoldingCapability::ScaffoldOutcome outcome =
        capability.CreateAssetScaffold(AssetScaffoldKind::ScreenPostProcessPass, "Foo");

    ASSERT_TRUE(outcome.success) << outcome.errorMessage;
    ASSERT_EQ(outcome.createdFiles.size(), 1u);
    EXPECT_EQ(outcome.createdFiles[0], "FooScreenPass.cpp");
    EXPECT_NE(outcome.reminderMessage.find("could not auto-wire"), std::string::npos);
    EXPECT_NE(outcome.reminderMessage.find("RegisterFooScreenPass(core)"), std::string::npos);

    // The old project's own Game.cpp is confirmed byte-for-byte unchanged -
    // never partially patched.
    EXPECT_EQ(ReadFile(gameCppPath), originalGameCppContent);
}

} // namespace gte
