// tests/Editor/ScreenPassPriorityAssignmentTests.cpp
//
// Tier-1 tests for src/Editor/ScreenPassPriorityAssignment.h's
// ComputeNextScreenPassPriority() (editor-core-separation-24 campaign,
// "Project Assembly On-Screen Render Feature Compositing" BIG-STEP 2,
// PHASE5 - PHASE5_PRIORITY_AUTO_ASSIGNMENT_HELPER.md, Step 4).
//
// This function needed its own dedicated header/source pair with EXTERNAL
// linkage (src/Editor/ScreenPassPriorityAssignment.h/.cpp) specifically so
// this test file could call it directly - every OTHER template-builder
// helper in EditorProjectLifecycleCapability.cpp lives in an anonymous
// namespace and is NOT callable from a separate translation unit at all
// (see tests/Editor/AssetScaffoldTemplateTests.cpp's own header comment,
// and PHASE4's tests/Editor/ScreenPassAutoWireTests.cpp for the identical
// precedent this file mirrors).

#include "Editor/ScreenPassPriorityAssignment.h"

#include <gtest/gtest.h>

#include <filesystem>
#include <fstream>
#include <string>

namespace gte {
namespace {

// A unique-per-test-run temp directory, cleaned up (best-effort) at the end
// of each test via its own destructor - never touches the real, production
// Projects/ tree. Mirrors AssetScaffoldTemplateTests.cpp's own
// TempScratchProjectDirectory helper shape.
class TempScratchAssetsDirectory {
public:
    explicit TempScratchAssetsDirectory(const std::string& uniqueSuffix)
        : m_path(std::filesystem::temp_directory_path() /
              ("gte_screen_pass_priority_tests_" + uniqueSuffix))
    {
        std::filesystem::remove_all(m_path);
    }

    ~TempScratchAssetsDirectory()
    {
        std::error_code ignored;
        std::filesystem::remove_all(m_path, ignored);
    }

    // Deliberately NOT created by the constructor - some tests need to
    // exercise "the Assets/ folder does not exist yet" directly.
    void Create() const
    {
        std::filesystem::create_directories(m_path);
    }

    const std::filesystem::path& Path() const { return m_path; }

private:
    std::filesystem::path m_path;
};

void WriteFile(const std::filesystem::path& path, const std::string& content)
{
    std::ofstream stream(path, std::ios::binary);
    stream << content;
}

std::string ScreenPassFileContent(std::int32_t priority)
{
    return
        "// Generated by the Editor's \"Create New Asset\" -> \"Screen "
        "Post-Process Pass...\" action.\n"
        "#include \"../../../src/Core/Core.h\"\n"
        "\n"
        "void RegisterFooScreenPass(gte::Core& core)\n"
        "{\n"
        "    core.RegisterProjectRenderFeature(\n"
        "        \"Foo.ScreenTint\",\n"
        "        gte::RenderFeatureStage::PostComposite,\n"
        "        gte::RenderFeatureBlendMode::AlphaOver,\n"
        "        /*priority=*/" + std::to_string(priority) + ",\n"
        "        [](gte::ProjectRenderFeatureContext& ctx) { (void)ctx; });\n"
        "}\n";
}

} // namespace

TEST(ScreenPassPriorityAssignmentTest, MissingAssetsFolderReturnsZero)
{
    TempScratchAssetsDirectory scratch("MissingFolder");
    // Deliberately never Create()'d.
    ASSERT_FALSE(std::filesystem::exists(scratch.Path()));

    EXPECT_EQ(ComputeNextScreenPassPriority(scratch.Path()), 0);
}

TEST(ScreenPassPriorityAssignmentTest, EmptyAssetsFolderReturnsZero)
{
    TempScratchAssetsDirectory scratch("EmptyFolder");
    scratch.Create();

    EXPECT_EQ(ComputeNextScreenPassPriority(scratch.Path()), 0);
}

TEST(ScreenPassPriorityAssignmentTest, NExistingFilesWithPrioritiesZeroThroughNMinusOneReturnsN)
{
    TempScratchAssetsDirectory scratch("NExisting");
    scratch.Create();

    constexpr int kN = 5;
    for (int i = 0; i < kN; ++i) {
        WriteFile(scratch.Path() / ("Screen" + std::to_string(i) + "ScreenPass.cpp"),
            ScreenPassFileContent(i));
    }

    EXPECT_EQ(ComputeNextScreenPassPriority(scratch.Path()), kN);
}

TEST(ScreenPassPriorityAssignmentTest, CaseInsensitiveFilenameMatchingStillCounts)
{
    TempScratchAssetsDirectory scratch("CaseInsensitive");
    scratch.Create();

    WriteFile(scratch.Path() / "FooSCREENPASS.CPP", ScreenPassFileContent(7));

    EXPECT_EQ(ComputeNextScreenPassPriority(scratch.Path()), 8);
}

TEST(ScreenPassPriorityAssignmentTest, UnrelatedFilesAreNeverCounted)
{
    TempScratchAssetsDirectory scratch("UnrelatedFiles");
    scratch.Create();

    // None of these end with "ScreenPass.cpp" (case-insensitive), so none
    // should ever be scanned/counted, even though some contain the token.
    WriteFile(scratch.Path() / "Foo.cpp", "/*priority=*/999");
    WriteFile(scratch.Path() / "FooRenderPass.cpp", "/*priority=*/999");
    WriteFile(scratch.Path() / "FooScreenPassBackup.txt", "/*priority=*/999");

    EXPECT_EQ(ComputeNextScreenPassPriority(scratch.Path()), 0);
}

TEST(ScreenPassPriorityAssignmentTest, MiddlePriorityDeletedStillYieldsHighestSurvivingPlusOne)
{
    TempScratchAssetsDirectory scratch("MiddleDeleted");
    scratch.Create();

    // Priorities 0, 1, 2 originally existed; the file holding priority 1 was
    // deleted from disk (outside the Editor) before this scan runs. The
    // correct answer is (highest SURVIVING priority) + 1 == 3, never a
    // plain re-numbered count (2) - the exact regression case Step 3.1 of
    // this phase's own file exists to prevent.
    WriteFile(scratch.Path() / "AlphaScreenPass.cpp", ScreenPassFileContent(0));
    WriteFile(scratch.Path() / "GammaScreenPass.cpp", ScreenPassFileContent(2));
    // BetaScreenPass.cpp (priority 1) deliberately never written - simulates
    // an out-of-band deletion.

    EXPECT_EQ(ComputeNextScreenPassPriority(scratch.Path()), 3);
}

TEST(ScreenPassPriorityAssignmentTest, FileWithNoParseableTokenIsSilentlySkipped)
{
    TempScratchAssetsDirectory scratch("NoToken");
    scratch.Create();

    // Hand-edited file where the "/*priority=*/" comment was removed or
    // reworded entirely - must be silently skipped, never treated as
    // priority 0 and never crashing the scan.
    WriteFile(scratch.Path() / "EditedScreenPass.cpp",
        "// priority comment removed by hand\n"
        "void RegisterEditedScreenPass(gte::Core&) {}\n");
    WriteFile(scratch.Path() / "NormalScreenPass.cpp", ScreenPassFileContent(4));

    EXPECT_EQ(ComputeNextScreenPassPriority(scratch.Path()), 5);
}

TEST(ScreenPassPriorityAssignmentTest, TokenFollowedByNonDigitGarbageIsSkippedNeverCrashes)
{
    TempScratchAssetsDirectory scratch("GarbageAfterToken");
    scratch.Create();

    WriteFile(scratch.Path() / "GarbageScreenPass.cpp", "/*priority=*/abc\n");
    WriteFile(scratch.Path() / "NormalScreenPass.cpp", ScreenPassFileContent(9));

    EXPECT_EQ(ComputeNextScreenPassPriority(scratch.Path()), 10);
}

TEST(ScreenPassPriorityAssignmentTest, NegativePriorityLiteralParsesCorrectlyAndParticipatesInMax)
{
    TempScratchAssetsDirectory scratch("NegativePriority");
    scratch.Create();

    WriteFile(scratch.Path() / "NegativeScreenPass.cpp", ScreenPassFileContent(-5));

    // Only a negative priority present -> highest surviving is -5 -> next is -4.
    EXPECT_EQ(ComputeNextScreenPassPriority(scratch.Path()), -4);
}

TEST(ScreenPassPriorityAssignmentTest, NegativePriorityDoesNotBeatAHigherPositiveSibling)
{
    TempScratchAssetsDirectory scratch("NegativeAndPositive");
    scratch.Create();

    WriteFile(scratch.Path() / "NegativeScreenPass.cpp", ScreenPassFileContent(-5));
    WriteFile(scratch.Path() / "PositiveScreenPass.cpp", ScreenPassFileContent(3));

    EXPECT_EQ(ComputeNextScreenPassPriority(scratch.Path()), 4);
}

} // namespace gte
