// tests/Editor/ScreenPassAutoWireTests.cpp
//
// Tier-1 tests for src/Editor/ScreenPassAutoWire.h's TryAutoWireRegisterCall()
// (editor-core-separation-24 campaign, "Project Assembly On-Screen Render
// Feature Compositing" BIG-STEP 2, PHASE4 -
// PHASE4_AUTO_WIRE_HELPER_TRY_AUTO_WIRE_REGISTER_CALL.md, Step 4).
//
// This function needed its own dedicated header/source pair with EXTERNAL
// linkage (src/Editor/ScreenPassAutoWire.h/.cpp) specifically so this test
// file could call it directly - every OTHER template-builder helper in
// EditorProjectLifecycleCapability.cpp lives in an anonymous namespace and
// is NOT callable from a separate translation unit at all (see
// tests/Editor/AssetScaffoldTemplateTests.cpp's own header comment).
//
// Anchor-line-shape note (see ScreenPassAutoWire.cpp's own header comment
// for the full story, confirmed via `ask_questions` before implementing):
// both anchors are genuine MULTI-LINE wrapped comment BLOCKS in the real,
// already-shipped template (EditorProjectLifecycleCapability.cpp's
// BuildGameStubCppContent()), not single lines - every content string below
// mirrors that real shape (copied verbatim from the real template),
// specifically so these tests exercise the REAL anchor-detection/insertion
// logic against REALISTIC content, not an oversimplified stand-in. The new
// line is expected to land immediately after the WHOLE anchor comment block
// ends, never splitting it.

#include "Editor/ScreenPassAutoWire.h"

#include <gtest/gtest.h>

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <string>

namespace gte {
namespace {

class TempScratchFile {
public:
    explicit TempScratchFile(const std::string& uniqueSuffix)
        : m_path(std::filesystem::temp_directory_path() /
              ("gte_screen_pass_auto_wire_tests_" + uniqueSuffix + ".cpp"))
    {
        std::filesystem::remove(m_path);
    }

    ~TempScratchFile()
    {
        std::error_code ignored;
        std::filesystem::remove(m_path, ignored);
    }

    const std::filesystem::path& Path() const { return m_path; }

private:
    std::filesystem::path m_path;
};

void WriteRawFile(const std::filesystem::path& path, const std::string& content)
{
    std::ofstream stream(path, std::ios::binary);
    stream << content;
}

std::string ReadRawFile(const std::filesystem::path& path)
{
    std::ifstream stream(path, std::ios::binary);
    return std::string((std::istreambuf_iterator<char>(stream)), std::istreambuf_iterator<char>());
}

int CountOccurrences(const std::string& haystack, const std::string& needle)
{
    int count = 0;
    std::size_t pos = 0;
    while ((pos = haystack.find(needle, pos)) != std::string::npos) {
        ++count;
        pos += needle.size();
    }
    return count;
}

// Byte-for-byte mirrors EditorProjectLifecycleCapability.cpp's own
// BuildGameStubCppContent() template shape (PHASE2) - both anchors present,
// each a real, seven-line wrapped comment block.
std::string BothAnchorsPresentContent()
{
    return
        "// FooGame.cpp - generated by the Editor's \"Create New Project\" action.\n"
        "// This is your project's Game half's entry point.\n"
        "#include \"../Libraries/ProjectAssemblyExports.h\"\n"
        "#include \"../../../src/Core/Core.h\"\n"
        "\n"
        "// GTE_AUTO_REGISTER_FORWARD_DECLARATIONS - do not remove or edit this\n"
        "// line. The Editor's \"Create\" scaffolding tools (Render Pass / Compute\n"
        "// Shader / Screen Post-Process Pass) insert a forward declaration for\n"
        "// each newly-scaffolded Register<Name>...(core) function directly BELOW\n"
        "// this line, automatically. Removing this comment does not break\n"
        "// anything - a future scaffold action simply cannot auto-wire itself in\n"
        "// anymore, and falls back to reminding you to wire it in by hand instead.\n"
        "\n"
        "namespace {\n"
        "\n"
        "void RegisterProject(gte::Core& core)\n"
        "{\n"
        "    // GTE_AUTO_REGISTER_ANCHOR - do not remove or edit this line. The\n"
        "    // Editor's \"Create\" scaffolding tools insert their own\n"
        "    // Register<Name>...(core); call directly ABOVE this comment,\n"
        "    // automatically, when they can find it. Removing this comment does\n"
        "    // not break anything - a future scaffold action simply cannot\n"
        "    // auto-wire itself in anymore, and falls back to reminding you to\n"
        "    // wire it in by hand instead.\n"
        "}\n"
        "\n"
        "} // namespace\n"
        "\n"
        "GTE_DEFINE_PROJECT_EXPORTS_GAME(RegisterProject)\n";
}

// Same content, but with a manually-commented-out PREVIOUSLY-auto-wired call
// line sitting inside the function body, above the body anchor block.
std::string BothAnchorsPresentWithCommentedOutCallContent()
{
    return
        "// FooGame.cpp - generated by the Editor's \"Create New Project\" action.\n"
        "#include \"../Libraries/ProjectAssemblyExports.h\"\n"
        "#include \"../../../src/Core/Core.h\"\n"
        "\n"
        "// GTE_AUTO_REGISTER_FORWARD_DECLARATIONS - do not remove or edit this\n"
        "// line. The Editor's \"Create\" scaffolding tools insert a forward\n"
        "// declaration directly BELOW this line, automatically.\n"
        "\n"
        "namespace {\n"
        "\n"
        "void RegisterProject(gte::Core& core)\n"
        "{\n"
        "    // RegisterFooScreenPass(core);\n"
        "    // GTE_AUTO_REGISTER_ANCHOR - do not remove or edit this line. The\n"
        "    // Editor's \"Create\" scaffolding tools insert their own call\n"
        "    // directly ABOVE this comment, automatically.\n"
        "}\n"
        "\n"
        "} // namespace\n"
        "\n"
        "GTE_DEFINE_PROJECT_EXPORTS_GAME(RegisterProject)\n";
}

// Forward-declarations anchor comment REMOVED entirely - only the body
// anchor survives.
std::string OnlyBodyAnchorContent()
{
    return
        "// FooGame.cpp - generated by the Editor's \"Create New Project\" action.\n"
        "#include \"../Libraries/ProjectAssemblyExports.h\"\n"
        "#include \"../../../src/Core/Core.h\"\n"
        "\n"
        "namespace {\n"
        "\n"
        "void RegisterProject(gte::Core& core)\n"
        "{\n"
        "    // GTE_AUTO_REGISTER_ANCHOR - do not remove or edit this line. The\n"
        "    // Editor's \"Create\" scaffolding tools insert their own call\n"
        "    // directly ABOVE this comment, automatically.\n"
        "}\n"
        "\n"
        "} // namespace\n"
        "\n"
        "GTE_DEFINE_PROJECT_EXPORTS_GAME(RegisterProject)\n";
}

// Body anchor comment REMOVED entirely - only the forward-declarations
// anchor survives.
std::string OnlyForwardDeclAnchorContent()
{
    return
        "// FooGame.cpp - generated by the Editor's \"Create New Project\" action.\n"
        "#include \"../Libraries/ProjectAssemblyExports.h\"\n"
        "#include \"../../../src/Core/Core.h\"\n"
        "\n"
        "// GTE_AUTO_REGISTER_FORWARD_DECLARATIONS - do not remove or edit this\n"
        "// line. The Editor's \"Create\" scaffolding tools insert a forward\n"
        "// declaration directly BELOW this line, automatically.\n"
        "\n"
        "namespace {\n"
        "\n"
        "void RegisterProject(gte::Core& core)\n"
        "{\n"
        "}\n"
        "\n"
        "} // namespace\n"
        "\n"
        "GTE_DEFINE_PROJECT_EXPORTS_GAME(RegisterProject)\n";
}

// Neither anchor present at all - the pre-PHASE2, old-style project shape.
std::string NeitherAnchorContent()
{
    return
        "// FooGame.cpp - generated by the Editor's \"Create New Project\" action.\n"
        "#include \"../Libraries/ProjectAssemblyExports.h\"\n"
        "#include \"../../../src/Core/Core.h\"\n"
        "\n"
        "namespace {\n"
        "\n"
        "void RegisterProject(gte::Core& /*core*/)\n"
        "{\n"
        "    // Intentionally empty - a freshly-created project registers nothing yet.\n"
        "}\n"
        "\n"
        "} // namespace\n"
        "\n"
        "GTE_DEFINE_PROJECT_EXPORTS_GAME(RegisterProject)\n";
}

} // namespace

TEST(ScreenPassAutoWireTest, BothAnchorsPresentInsertsBothLinesCorrectlyPositioned)
{
    TempScratchFile scratch("BothAnchorsPresent");
    const std::string original = BothAnchorsPresentContent();
    WriteRawFile(scratch.Path(), original);

    const bool result = TryAutoWireRegisterCall(scratch.Path(), "RegisterFooScreenPass");

    EXPECT_TRUE(result);
    const std::string content = ReadRawFile(scratch.Path());

    // Both new lines present, exactly once each.
    EXPECT_EQ(CountOccurrences(content, "void RegisterFooScreenPass(gte::Core& core);"), 1);
    EXPECT_EQ(CountOccurrences(content, "    RegisterFooScreenPass(core);"), 1);

    // Placement (Option B, user-confirmed): immediately AFTER the whole
    // anchor comment block ends - never splitting it.
    EXPECT_NE(content.find(
        "// anymore, and falls back to reminding you to wire it in by hand instead.\n"
        "void RegisterFooScreenPass(gte::Core& core);\n"
        "\n"
        "namespace {"),
        std::string::npos);
    EXPECT_NE(content.find(
        "    // wire it in by hand instead.\n"
        "    RegisterFooScreenPass(core);\n"
        "}\n"),
        std::string::npos);

    // Every original line survives - exactly two new lines were added, no
    // existing line was edited/removed.
    EXPECT_NE(content.find("GTE_AUTO_REGISTER_FORWARD_DECLARATIONS"), std::string::npos);
    EXPECT_NE(content.find("GTE_AUTO_REGISTER_ANCHOR"), std::string::npos);
    EXPECT_NE(content.find("GTE_DEFINE_PROJECT_EXPORTS_GAME(RegisterProject)"), std::string::npos);
    EXPECT_EQ(std::count(content.begin(), content.end(), '\n'),
        std::count(original.begin(), original.end(), '\n') + 2);
}

TEST(ScreenPassAutoWireTest, ForwardDeclAnchorMissingReturnsFalseFileUnchanged)
{
    TempScratchFile scratch("ForwardDeclMissing");
    const std::string original = OnlyBodyAnchorContent();
    WriteRawFile(scratch.Path(), original);

    const bool result = TryAutoWireRegisterCall(scratch.Path(), "RegisterFooScreenPass");

    EXPECT_FALSE(result);
    EXPECT_EQ(ReadRawFile(scratch.Path()), original);
}

TEST(ScreenPassAutoWireTest, BodyAnchorMissingReturnsFalseFileUnchanged)
{
    TempScratchFile scratch("BodyAnchorMissing");
    const std::string original = OnlyForwardDeclAnchorContent();
    WriteRawFile(scratch.Path(), original);

    const bool result = TryAutoWireRegisterCall(scratch.Path(), "RegisterFooScreenPass");

    EXPECT_FALSE(result);
    EXPECT_EQ(ReadRawFile(scratch.Path()), original);
}

TEST(ScreenPassAutoWireTest, BothAnchorsMissingReturnsFalseFileUnchanged)
{
    TempScratchFile scratch("BothAnchorsMissing");
    const std::string original = NeitherAnchorContent();
    WriteRawFile(scratch.Path(), original);

    const bool result = TryAutoWireRegisterCall(scratch.Path(), "RegisterFooScreenPass");

    EXPECT_FALSE(result);
    EXPECT_EQ(ReadRawFile(scratch.Path()), original);
}

TEST(ScreenPassAutoWireTest, IdempotentSecondCallForSameNameWritesNothingNew)
{
    TempScratchFile scratch("Idempotent");
    WriteRawFile(scratch.Path(), BothAnchorsPresentContent());

    const bool firstResult = TryAutoWireRegisterCall(scratch.Path(), "RegisterFooScreenPass");
    ASSERT_TRUE(firstResult);
    const std::string afterFirstCall = ReadRawFile(scratch.Path());

    const bool secondResult = TryAutoWireRegisterCall(scratch.Path(), "RegisterFooScreenPass");

    EXPECT_TRUE(secondResult);
    EXPECT_EQ(ReadRawFile(scratch.Path()), afterFirstCall);
}

TEST(ScreenPassAutoWireTest, CommentedOutCallTreatedAsNotWiredInsertsFreshActiveCall)
{
    TempScratchFile scratch("CommentedOutCall");
    WriteRawFile(scratch.Path(), BothAnchorsPresentWithCommentedOutCallContent());

    const bool result = TryAutoWireRegisterCall(scratch.Path(), "RegisterFooScreenPass");

    EXPECT_TRUE(result);
    const std::string content = ReadRawFile(scratch.Path());

    // The OLD, manually-commented-out call line survives, untouched.
    EXPECT_NE(content.find("    // RegisterFooScreenPass(core);\n"), std::string::npos);
    // A NEW, active (uncommented) call line was inserted too - never
    // mistaking the commented-out line for "already wired".
    EXPECT_NE(content.find("\n    RegisterFooScreenPass(core);\n}\n"), std::string::npos);
    // Exactly one commented occurrence and one active occurrence - two total.
    EXPECT_EQ(CountOccurrences(content, "RegisterFooScreenPass(core);"), 2);
}

TEST(ScreenPassAutoWireTest, TwoDifferentNamesCalledInSequenceBothPresentAndCorrectlyPositioned)
{
    TempScratchFile scratch("TwoDifferentNames");
    WriteRawFile(scratch.Path(), BothAnchorsPresentContent());

    const bool firstResult = TryAutoWireRegisterCall(scratch.Path(), "RegisterAlphaScreenPass");
    ASSERT_TRUE(firstResult);
    const bool secondResult = TryAutoWireRegisterCall(scratch.Path(), "RegisterBetaScreenPass");
    ASSERT_TRUE(secondResult);

    const std::string content = ReadRawFile(scratch.Path());

    // Both forward declarations present, each exactly once - the second
    // insertion's own point resolution was not thrown off by the first
    // insertion's already-shifted line indices (this file re-reads fresh
    // from disk on every call, so this is also a real regression proof for
    // that exact hazard).
    EXPECT_EQ(CountOccurrences(content, "void RegisterAlphaScreenPass(gte::Core& core);"), 1);
    EXPECT_EQ(CountOccurrences(content, "void RegisterBetaScreenPass(gte::Core& core);"), 1);
    // Both active call lines present, each exactly once.
    EXPECT_EQ(CountOccurrences(content, "    RegisterAlphaScreenPass(core);"), 1);
    EXPECT_EQ(CountOccurrences(content, "    RegisterBetaScreenPass(core);"), 1);
    // Neither anchor's own comment block was corrupted.
    EXPECT_NE(content.find("GTE_AUTO_REGISTER_FORWARD_DECLARATIONS"), std::string::npos);
    EXPECT_NE(content.find("GTE_AUTO_REGISTER_ANCHOR"), std::string::npos);
}

TEST(ScreenPassAutoWireTest, CorruptedBinaryGarbageInputFailsSafelyNeverCrashes)
{
    TempScratchFile scratch("CorruptedBinary");
    const std::string garbage = std::string("\x00\x01\xFF\xFE\x80\x81 not a real cpp file at all \x00", 40);
    WriteRawFile(scratch.Path(), garbage);

    const bool result = TryAutoWireRegisterCall(scratch.Path(), "RegisterFooScreenPass");

    EXPECT_FALSE(result);
    EXPECT_EQ(ReadRawFile(scratch.Path()), garbage);
}

TEST(ScreenPassAutoWireTest, NonExistentFileReturnsFalse)
{
    const std::filesystem::path nonExistentPath =
        std::filesystem::temp_directory_path() / "gte_screen_pass_auto_wire_tests_DoesNotExist.cpp";
    std::filesystem::remove(nonExistentPath);
    ASSERT_FALSE(std::filesystem::exists(nonExistentPath));

    const bool result = TryAutoWireRegisterCall(nonExistentPath, "RegisterFooScreenPass");

    EXPECT_FALSE(result);
    EXPECT_FALSE(std::filesystem::exists(nonExistentPath));
}

} // namespace gte
